version: '2'
distribution_spec:
  description: Quick start template for running Llama Stack with several popular providers
  providers:
    inference:
    - remote::fireworks
    - remote::vllm
    - inline::sentence-transformers
    vector_io:
    - remote::chromadb
    safety:
    - inline::llama-guard
    agents:
    - inline::meta-reference
    telemetry:
    - inline::meta-reference
    eval:
    - inline::meta-reference
    datasetio:
    - remote::huggingface
    - inline::localfs
    scoring:
    - inline::basic
    - inline::llm-as-judge
    - inline::braintrust
    tool_runtime:
    - remote::brave-search
    - remote::tavily-search
    - inline::rag-runtime
    - remote::model-context-protocol
image_type: conda
additional_pip_packages:
- asyncpg
- sqlalchemy[asyncio]
